name: Purge Cache

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/npm/@trendyol/baklava@beta
