name: 'Release new version'

on:
  workflow_run:
    workflows:
      - Verify and Preview
    types: [completed]
    branches: [main, next, 1.0.x]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build Grace
        run: npm run build
      - name: Publish to NPM
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.TRENDYOL_JS_NPM_TOKEN }}
