name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Publish to NPM
        run: npx semantic-release --dry-run
        env:
          NPM_TOKEN: ${{ secrets.TRENDYOL_JS_NPM_TOKEN }}
