name: 'Release new version'

on:
  push:
    branches:
      - main
      - next
      - 1.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/verify
      - name: Publish to NPM
        run: npx semantic-release --dry-run
        env:
          NPM_TOKEN: ${{ secrets.TRENDYOL_JS_NPM_TOKEN }}
