name: 'Verify and Release'

on:
  push:
    branches:
      - main
      - next
      - 1.0.x

jobs:
  verify:
    uses: trendyol/grace/.github/workflows/verify.yml@next
  preview:
    uses: trendyol/grace/.github/workflows/publish-storybook.yml@next
    needs: verify
  release:
    uses: trendyol/grace/.github/workflows/release.yml@next
    needs: verify
